spring:
  application:
    name: Cadastro de Jogadores

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: sa
    password: ""

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create

  server:
    error:
      include-stacktrace: never