spring:
  profiles:
    active: test

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /api-docs/swagger-config
    urls:
      - url: /api/swagger.yaml
        name: Jogadores API